### ISSUE TITLE
Transaction for upload-nfts complete, but files inaccessible

### ISSUE THREAD

**Issue by nickr2001** [CalebEverett/arloader#23]
Metadata:
https://viewblock.io/arweave/tx/CYxzfb6gKuU1-KEUAVQUDZTpBOOi8iLcGA71EuOc9jk

Images:
https://viewblock.io/arweave/tx/yeFIaMr8plqwgvW6jQqOm7CQYLXl2HWTf8NfuAtADi8

I used the upload-nfts command to upload a test set of 100 NFTs, but even after several hundred confirmations none of the bundled transactions return anything but the standard 'not found' page on arweave.net.

Here's an example of one of the bundled transactions that should return an image: https://arweave.net/-DM0oTxVYX8esq8fn79ifxAoNJRpyZHhXmYTsVAGMjE

It doesn't seem to be a one off issue for me; I first ran into this issue yesterday, and I eventually gave up on this transaction and tried to use the same command again this morning to the same result.

In case these are needed as well, these are the links to the new transaction bundles:
Images:
https://viewblock.io/arweave/tx/23-cH3-AAYCYPCp43fD1Im1iNgED3NoDcNwTAisIXOY

Metadata:
https://viewblock.io/arweave/tx/hK9cpjqHYnUi3IwIY_om8pMNgxcgInAR2Tt2fmvFnmM

**Comment by CalebEverett** [comment]
Hi, I'll take a look - this is usually related to arweave/gateway issues. Apparently there has been a lot of network congestion over the last several days.

**Comment by nickr2001** [comment]
Great, thank you for looking into it.

**Comment by CalebEverett** [comment]
Likely a bundle parsing issue with the gateway. I take from the bundle confirmation and the parsing of the data items evident on viewblock that the bundles have been successfully written to the chain and the fact that they aren't available at the links to the data items to mean there is a problem with the gateway.

Until the gateway issues are resolved, I think you have two options:
1. Upload individual items instead of bundles - looks like you've gotten this figured out with arkb. With arloader you can pass the `--no-bundle` flag, but that unfortunately isn't available for the `upload-nfts` command. There is a [doc](https://github.com/CalebEverett/arloader/blob/master/docs/upload_nfts_steps.md) with some detail on how to complete the steps individually.  The downside on this approach is that you are going to clog up the network further, arweave can only write 1,000 tx per block, approx. every 2 minutes. So if you go this route, check to make sure the pending transactions `arloader pending` aren't already close to or in excess of 1,000, and then upload in batches of a couple hundred or so.
2. The better option, is just to use bundlr. I don't think they have the equivalent, `upload-nfts` command, but you could follow the same basic flow described in the doc I linked. The upside here is that your files will likely be immediately available since bundlr is heavily support by arweave and includes a feature where they cache your uploaded files and the main arweave gateway will look to that cache if it doesn't find them in it's own cache. You may not see your tx ids on the network right away, due to network congestion, but they "guarantee" to get them there with the initial id returned, basically retrying them until they stick as I understand it. But the net is you can use your links right away and then just check back in a day or so to make sure you see them on viewblock or gql. The cost on that is something like a $3 gb premium, which in my mind is way worth it, if you're just trying to get your files uploaded do you can actually create some nfts.

**Comment by nickr2001** [comment]
Interestingly I did try uploading the same batch of images via arkb as a bundle as well and those images are accessible through the gateway. Is there any meaningful difference between how arloader and arkb upload bundles?

bundle transaction sent via arkb: 
https://viewblock.io/arweave/tx/KZQEGDwXxmOrvf-GcOMytd6eFYTPGO3oJ2Dd30ren7s

**Comment by CalebEverett** [comment]
That looks like an individual transaction https://viewblock.io/arweave/address/4XLIblezt71RzecXAnm4BRqbyAaqUN4O9yGO5r-JMo0. As far as bundles, I think arkb has the option of either native or through bundlr. Not sure what the default is. At the end of the day, everybody has to create and upload bundles in the same format. There can be differences in error handling and retry logic and more importantly on the caching, but as far as I know, bundlr is the only service that has the special caching arrangement.

**Comment by nickr2001** [comment]
It looks like the initial bundle I sent is working now. Thanks for the clarification!
