### ISSUE TITLE
Allow setting solana_url

### ISSUE THREAD

**Issue by znebby** [CalebEverett/arloader#4]
This would let us use private nodes or chains other than the mainnet

**Comment by CalebEverett** [comment]
Good point - I've seen a lot of private rpc usage. I can add that in.
Although with the bundled transaction format, there are many fewer
transactions and rate limits shouldn't be a problem.

**Comment by CalebEverett** [comment]
Actually, I don't think this really works. Non-main net chains don't work because you need to have actually transferred SOL in order to pay for the signing of the AR transaction, which only has a mainnet, no dev net. Also, the concept of submitting a url to the signing service that it then uses to sign is beyond the scope of the service. Users submit signed, but unsubmitted transactions to the service api. It is then up to the service api to decide where it wants to submit those transactions to get them recorded and verified.

**Comment by CalebEverett** [comment]
Actually, I don't think this really works. Non-main net chains don't work because you need to have actually transferred SOL in order to pay for the signing of the AR transaction, which only has a mainnet, no dev net. Also, the concept of submitting a url to the signing service that it then uses to sign is beyond the scope of the service. Users submit signed, but unsubmitted transactions to the service api. It is then up to the service api to decide where it wants to submit those transactions to get them recorded and verified.

**Comment by znebby** [comment]
Actually - it works with Devnet Solana, with the tool in Metaplex. There may be some restrictions on the file-size, but it's good for testing.

**Comment by CalebEverett** [comment]
I think they are paying actual AR to make that work.
