### ISSUE TITLE
Upload command when using --with-sol should not require --ar-keypair-path

### ISSUE THREAD

**Issue by znebby** [CalebEverett/arloader#5]
Currently I need to create a dummy ar wallet, even though I'm not using it.

**Comment by CalebEverett** [comment]
You need an AR wallet to sign your data items so that you own them even
though the bundle transaction they are included in is owned by the service
wallet if you pass `--with-sol`.

**Comment by znebby** [comment]
OK - I'm not that familiar with how ARWeave works. What does "owning" give you since the files are public and can never be taken down?

Metaplex comes with a tool which allows you to upload to ARWeave without specifying any AR wallet (only SOL).

**Comment by CalebEverett** [comment]
It doesn't really give you any rights since everything uploaded to Arweave is immutable. It's possible to have arloader use a default wallet, though, as a convenience. I'll see if I can find a way to do that that is transparent. I'd like to keep arloader as decentralized as possible.

**Comment by CalebEverett** [comment]
For the ui on this, I was planning on adding a flag `--ar-courtesy-wallet` that you could pass if you passed `--with-sol` and `--sol-keypair-path` that would use an included wallet to sign data items so that you didn't have to go get an ar wallet. The other alternative would be to just use the included wallet (again just in the case where you were trying to pay with sol) unless you included with with `--ar-keypair-path` or in the AR_KEYPAIR_PATH environment variable. Even though the first approach requires passing an additional argument, I prefer that one as it makes it explicit that your data items won't be owned by your wallet.

What do you think?

**Comment by znebby** [comment]
The second option sounds simpler to me. But perhaps I would prefer the first one - if I understood what "owning" data items you upload actually gives you.

**Comment by CalebEverett** [comment]
I think they key benefit would be that if you ever wanted to search for your files on arweave, you'd be able to do that with that wallet. You could add a tag and search by that as well, though.

**Comment by CalebEverett** [comment]
https://github.com/CalebEverett/arloader/releases/tag/v0.1.38
